{{- $service := .Values.relayer -}}
{{- if $service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuel-hyperlane-service.fullname" . }}-relayer
  labels:
    {{ - include "fuel-hyperlane-service.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-relayer
spec:
  {{ - if not $service.autoscaling.enabled }}
  replicas: {{ $service.replicaCount }}
  {{ - end }}
  selector:
    matchLabels:
      {{ - include "fuel-hyperlane-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-relayer
  template:
    metadata:
      {{ - with $service.podAnnotations }}
      annotations:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      labels:
        {{ - include "fuel-hyperlane-service.labels" . | nindent 8 }}
        app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-relayer
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{ - if $service.serviceAccount.create }}
      serviceAccountName: {{ include "$service.serviceAccount.name" . }}
      {{ - end }}

      {{ - with $service.podSecurityContext }}
      securityContext:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}

      containers:
        - name: {{ include "fuel-explorer.fullname" . }}-relayer
          {{- with $service.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{ - end }}
          
          image: "{{ .Values.image.repository }}:{{ $service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{ - with $service.image.startCommand }}
          command:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          {{ - with $service.image.startCommandArgs }}
          args:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          
          env:
            - name: SERVICE
              value: relayer
          envFrom:
            - configMapRef:
                name: {{ include "fuel-hyperlane.fullname" . }}-relayer
            - secretRef:
                name: {{ include "fuel-hyperlane.fullname" . }}-relayer
        
          ports:
            - name: http
              containerPort: {{ $service.service.port }}
              protocol: TCP
          
          {{ - if $service.healthcheck.enabled }}
          {{ - with $service.livenessProbe }}
          livenessProbe:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          {{ - with $service.readinessProbe }}
          readinessProbe:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          {{ - end }}
         
          resources:
            {{- toYaml $service.resources | nindent 12 }}

          {{ - with $service.volumeMounts }}
          volumeMounts:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
      {{ - with $service.volumes }}
      volumes:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      {{ - with $service.nodeSelector }}
      nodeSelector:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      {{ - with $service.affinity }}
      affinity:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      {{ - with $service.tolerations }}
      tolerations:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
{{- end }}