{{- $service := .Values.relayer -}}
{{- if and ($service.enabled) ($service.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "$service.serviceAccount.name" . }}
  labels:
    {{- include "fuel-hyperlane-service.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-relayer

  {{- with $service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $service.serviceAccount.automount }}
{{- end }}
