{{- $service := .Values.validator -}}
{{- if and ($service.enabled) ($service.service.create) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuel-hyperlane-service.fullname" . }}-validator
  labels:
    {{- include "fuel-hyperlane-service.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-validator
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fuel-hyperlane-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/service: {{ include "fuel-hyperlane-service.fullname" . }}-validator
{{- end }}
