name: Build and Push Monorepo Image to ECR
on:
  push:
    branches: [main]
    tags:
      - '**'

concurrency:
  group: build-push-monorepo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # checkout local hyperlane clone until changed merged upstream
      - uses: actions/checkout@v4
        with:
          repository: fuel-infrastructure/hyperlane-monorepo
          ref: feat/fuel-integration
          submodules: recursive

      - name: Configure AWS credentials for ECR publishing
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::024848458133:role/github_oidc_FuelLabs_fuel-hyperlane-service
          aws-region: us-east-1 # ecr public is only in us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag data
        id: taggen
        run: |
          echo "TAG_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo "TAG_SHA=$(echo '${{ github.event.pull_request.head.sha || github.sha }}' | cut -b 1-7)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ steps.login-ecr.outputs.registry }}/fuel-hyperlane-service
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.taggen.outputs.TAG_SHA }}-${{ steps.taggen.outputs.TAG_DATE }}

      - name: Read .registryrc
        shell: bash
        run: |
          REGISTRY_VERSION=$(cat .registryrc)
          echo "REGISTRY_VERSION=$REGISTRY_VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REGISTRY_COMMIT=${{ env.REGISTRY_VERSION }}
